services:
  - type: web
    name: mysite
    env: python
    buildCommand: ./build.sh
    startCommand: python create_admin.py && gunicorn mysite.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"