# Generated by Django 6.0.5 on 2026-05-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('reference', 'Справочник'), ('work', 'Учебная работа'), ('interactive', 'Интерактивный урок'), ('classroom', 'Классное руководство')], max_length=20, verbose_name='Тип материала'),
        ),
    ]
