# Generated by Django 6.0.5 on 2026-05-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_material_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='content_type',
            field=models.CharField(choices=[('link', 'Ссылка'), ('text', 'Текст'), ('photo', 'Фото')], default='link', max_length=10, verbose_name='Тип содержимого'),
        ),
        migrations.AddField(
            model_name='material',
            name='photo',
            field=models.ImageField(blank=True, upload_to='materials/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='material',
            name='text_content',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='material',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
    ]
