# Generated by Django 6.0.5 on 2026-05-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_create_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль для входа на сайт')),
            ],
            options={
                'verbose_name': 'Пароль сайта',
                'verbose_name_plural': 'Пароль сайта',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, upload_to='files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='material',
            name='content_type',
            field=models.CharField(choices=[('link', 'Ссылка'), ('text', 'Текст'), ('photo', 'Фото'), ('file', 'Файл')], default='link', max_length=10, verbose_name='Тип содержимого'),
        ),
    ]
